### ISSUE TITLE
generate killed

### ISSUE THREAD

**Issue by hlx70375** [JamesPan/hexo-ruby-character#1]
intalled hexo-ruby-character,write {% ruby someting|someting %}in my _.md ,save and run `hexo generate`,it back `killed`
安装完这个插件后，我在_.md文件里写入 {% ruby 测试|测试 %}，运行`hexo generate`会提示`killed`

**Comment by jamespan** [comment]
@hlx70375 More info please, like the version of Node.js, Hexo, etc.

**Comment by hlx70375** [comment]
我在同一个vps里面，新建一个hexo安装这个插件是成功的。但是在这个原来hexo目录安装出现下面的错误。

> Now using node v4.2.6 (npm v2.14.12)
> 安装时的出错信息：

```
npm install hexo-ruby-character --save
-
> nodejieba@1.4.7 install /home/dg/hexo/node_modules/hexo-ruby-character/node_modules/pinyin/node_modules/nodejieba
> node-gyp rebuild

make: Entering directory '/home/dg/hexo/node_modules/hexo-ruby-character/node_modules/pinyin/node_modules/nodejieba/build'
  CXX(target) Release/obj.target/nodejieba/lib/index.o
  CXX(target) Release/obj.target/nodejieba/lib/nodejieba.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
nodejieba.target.mk:95: recipe for target 'Release/obj.target/nodejieba/lib/nodejieba.o' failed
make: *** [Release/obj.target/nodejieba/lib/nodejieba.o] Error 4
make: Leaving directory '/home/dg/hexo/node_modules/hexo-ruby-character/node_modules/pinyin/node_modules/nodejieba/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dg/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-042stab108.8
gyp ERR! command "/home/dg/.nvm/versions/node/v4.2.6/bin/node" "/home/dg/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dg/hexo/node_modules/hexo-ruby-character/node_modules/pinyin/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing nodejieba@1.4.7
hexo-ruby-character@1.0.6 node_modules/hexo-ruby-character
└── pinyin@2.6.2 (commander@1.1.1)
```
